chore: update commit lint config

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,7 @@
 #!/bin/sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npx lint-staged 
+echo '🧐 Checking for lint errors...'
+sleep 2
+npx lint-staged ||
+(echo '😕 Lint errors or tests failed. Please fix them before commiting.' && exit 1)
